"""Update column in if,Otp,Usre table 

Revision ID: d6180815b511
Revises: 30284cf4d7d7
Create Date: 2024-07-12 15:39:32.561760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6180815b511'
down_revision: Union[str, None] = '30284cf4d7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
